### PR TITLE
Fixup: Adding histograms for networks by file size

### LINKED ISSUE #40: Individual Reports for Each Network/Site
We'd like to have individual reports for each network+website so that you can break down metrics further than what we're currently reporting.

### PR DESCRIPTION
**Pull request by purukaushik**
⚠️ Dont merge yet! ⚠️ 
Basic working histogram for file size is up, but fixing small cosmetic UX issues with graphs.
Fixes #40

### CODE REVIEW

**Comment by purukaushik** [comment]
Some issues with histograms with [plot.ly](https://plot.ly/) :
1.  Many records with one size:
Many records with one size
2. Outliers
Outliers

**Comment by FrancescoSTL** [comment]
@purukaushik is this ready for r?

**Comment by FrancescoSTL** [comment]
Reviewing right now. @purukaushik can you sort descending by # of files (for the file type table)?

**Comment by purukaushik** [comment]
i.e #Assets right?

**Comment by FrancescoSTL** [comment]
@purukaushik yep!

**Comment by purukaushik** [comment]
r again... fixed that

**Comment by FrancescoSTL** [comment]
Looks good! R+ and pushing to prod

**Pull request merged**
