### PR TITLE
MongoDB URL unexposé

### LINKED ISSUE #4: Remove MongoDB Connection String
Convert mongodb connection string to a environmental variable on heroku side so that people don't try to connect and do bad things to it. Have localhost mongoDB for development/testing branches.

### PR DESCRIPTION
**Pull request by purukaushik**
Fixes #4 
Have utilized heroku env var MONGODB_URI to get url.

### CODE REVIEW

**Comment by purukaushik** [comment]
- a cleaner JSON in README.md

**Comment by FrancescoSTL** [comment]
Thanks, @purukaushik! r+ 🌈

**Comment by FrancescoSTL** [comment]
Confirmed working connected to Heroku in prod @purukaushik

**Comment by purukaushik** [comment]
classic :ok_hand:

**Pull request merged**
